site_name: Buhos-App API Documentation
site_url: https://tu-usuario.github.io/tu-repositorio/

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Portal de Inicio: index.md
  - Servicios de Aulas: endpoints.md
  - Infraestructura y Capas: arquitectura.md